[package]
name = "propositional"
description = "Propositional Logic"
version = "0.1.0-alpha.2"
edition = "2021"
repository = "https://github.com/PawelJastrzebski/propositional"
license = "MIT"
keywords = ["logic", "propositional-logic"]

[dependencies]
